import Logo from "./imgs/logo.png"
import 'bootstrap/dist/css/bootstrap.min.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href={ Logo.src } />
      </head>
      <body>{children}</body>
    </html>
  )
}
